[package]
name = "nat"
version = "1.0.8"
authors = ["Will Lane <williamlane923@gmail.com>"]
description = "nat - the 'ls' replacement you never knew you needed"
license = "MIT"
repository = "https://github.com/willdoescode/nat"
edition = "2018"

[dependencies]
termion = "*"
chrono = "*"
users = "*"
pretty-bytes = "*"
ansi_term = "*"
structopt = "*"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
